# Generated by Django 3.2 on 2021-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Erasers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
            ],
        ),
    ]
